# -*- mode: ruby -*-
	#vi: set ft=ruby :

	Vagrant.configure("2") do |config|
	  config.vm.box = "proyecto"
	  config.vm.network :private_network, ip: "192.168.2.2"
	  config.vm.provision "ansible" do |ansible| 
   	   ansible.inventory_path = "ansible_hosts"
  	      ansible.playbook = "playbook.yml"
	end
