---
- hosts: all
  sudo: yes
  user: vagrant
  tasks:
    - name: Actualizar paquetes de los repositorios
      apt: update_cache=yes
    - name: Instalar Git
      apt: name=git state=present
    - name: Instalar Python
      apt: name=python state=present
    - name: Instalar Django
      apt: name=python-django state=present
